'use strict';

const O=(ja,en,tags=[])=>({ja,en,tags});
const C=(id,icon,label,desc,fields)=>({id,icon,label,desc,fields});
const F=(id,label,level,options,def=0)=>({id,label,level,type:'select',options,default:def});
const R=(id,label,level,min,max,step,def,suffix='')=>({id,label,level,type:'range',min,max,step,default:def,suffix});

const cats={
  breed:[O('雑種・日本猫','domestic mixed-breed cat',['natural','japan']),O('ラグドール','Ragdoll cat',['cute','photo']),O('メインクーン','Maine Coon cat',['photo','cinema']),O('マンチカン','Munchkin cat',['cute']),O('スコティッシュフォールド','Scottish Fold cat',['cute']),O('ブリティッシュショートヘア','British Shorthair cat',['cute','photo']),O('アメリカンショートヘア','American Shorthair cat',['natural']),O('ノルウェージャンフォレストキャット','Norwegian Forest cat',['photo','fantasy']),O('サイベリアン','Siberian cat',['photo']),O('ベンガル','Bengal cat',['wild','photo']),O('シャム','Siamese cat',['elegant']),O('ロシアンブルー','Russian Blue cat',['elegant']),O('アビシニアン','Abyssinian cat',['elegant']),O('ソマリ','Somali cat',['elegant']),O('ペルシャ','Persian cat',['cute']),O('エキゾチックショートヘア','Exotic Shorthair cat',['cute']),O('スフィンクス','Sphynx cat',['chaos','photo']),O('コーニッシュレックス','Cornish Rex cat',['elegant']),O('セルカークレックス','Selkirk Rex cat',['cute']),O('バーマン','Birman cat',['cute']),O('バーミーズ','Burmese cat',['elegant']),O('シンガプーラ','Singapura cat',['cute']),O('アメリカンカール','American Curl cat',['cute']),O('ボンベイ','Bombay cat',['cinema']),O('オシキャット','Ocicat',['wild']),O('ラガマフィン','Ragamuffin cat',['cute'])],
  age:[O('生後1〜2か月','a 1–2 month old tiny kitten',['cute']),O('生後3〜4か月','a 3–4 month old kitten',['cute']),O('生後5〜8か月','a 5–8 month old adolescent kitten'),O('1歳前後','a young one-year-old cat'),O('2〜3歳','a 2–3 year old young adult cat',['photo']),O('4〜7歳','a mature 4–7 year old adult cat',['natural']),O('8〜12歳','an 8–12 year old senior cat'),O('高齢猫','an elderly senior cat')],
  sex:[O('指定なし','sex unspecified'),O('オス','male cat'),O('メス','female cat')],
  body:[O('とても小柄','very petite'),O('小柄','small and slender'),O('標準','average build',['natural']),O('大柄','large-bodied'),O('巨大','very large and imposing',['cinema']),O('細身','lean and graceful',['elegant']),O('筋肉質','athletic and muscular'),O('丸っこい','round-bodied',['cute']),O('ぽっちゃり','chubby',['cute']),O('かなりぽっちゃり','very chubby',['cute','chaos'])],
  personality:[O('おっとり','gentle and laid-back',['cute']),O('甘えん坊','affectionate and cuddly',['cute']),O('好奇心旺盛','highly curious',['natural']),O('臆病','timid and cautious'),O('やんちゃ','mischievous and energetic'),O('食いしん坊','food-loving',['chaos']),O('気高い','proud and regal',['cinema']),O('ツンデレ','aloof but secretly affectionate'),O('警戒心強め','alert and wary'),O('虚無','absurdly blank and existential',['chaos'])],
  head:[O('丸顔','round face',['cute']),O('小顔','small delicate face'),O('幅広','broad face'),O('逆三角形','triangular face'),O('細長い','long narrow face'),O('ぺちゃ顔','flat brachycephalic face',['cute'])],
  eyeColor:[O('ブルー','clear blue eyes',['cute']),O('水色','pale aqua eyes'),O('グリーン','green eyes'),O('黄緑','yellow-green eyes'),O('琥珀','amber eyes'),O('ゴールド','golden eyes'),O('銅色','copper eyes'),O('ブラウン','brown eyes'),O('オッドアイ','odd eyes, one blue and one amber',['cute','fantasy'])],
  eyeShape:[O('まん丸','large round eyes',['cute']),O('アーモンド','almond-shaped eyes',['elegant']),O('つり目','slightly upturned eyes'),O('たれ目','slightly downturned gentle eyes',['cute']),O('細目','narrow relaxed eyes'),O('半目','half-lidded sleepy eyes',['chaos'])],
  pupil:[O('自然','natural pupils'),O('細い縦長','narrow vertical pupils'),O('大きめ','dilated pupils',['cute']),O('真ん丸','very large round pupils',['cute'])],
  ears:[O('標準の立ち耳','upright natural ears'),O('大きな尖り耳','large pointed ears'),O('小さな耳','small ears'),O('折れ耳','folded ears',['cute']),O('反り耳','back-curled ears'),O('耳毛ふさふさ','prominent ear tufts',['photo'])],
  earPose:[O('前向き','ears facing forward'),O('少し横向き','ears tilted slightly sideways'),O('イカ耳','airplane ears flattened sideways',['chaos']),O('後ろ向き','ears angled backward'),O('左右非対称','asymmetrical ear positions')],
  nose:[O('ピンク','pink nose',['cute']),O('黒','black nose'),O('濃い茶','dark brown nose'),O('グレー','gray nose'),O('まだら','mottled nose')],
  furLength:[O('無毛','hairless'),O('極短毛','very short sleek fur'),O('短毛','short fur',['natural']),O('中毛','medium-length fur'),O('長毛','long fur',['cute','photo']),O('超長毛','extremely long luxurious fur',['fantasy'])],
  furTexture:[O('なめらか','smooth sleek fur'),O('サラサラ','silky fur',['elegant']),O('ふわふわ','soft fluffy fur',['cute']),O('もこもこ','dense plush fur',['cute']),O('巻き毛','curly fur'),O('少し乱れた毛','slightly tousled fur',['natural']),O('濡れた毛','wet clumped fur',['chaos'])],
  furDensity:[O('薄め','light coat density'),O('標準','normal coat density'),O('毛量多め','thick dense coat',['photo']),O('爆毛','extremely voluminous fluffy coat',['cute','chaos'])],
  color:[O('白','white',['cute']),O('黒','black',['cinema']),O('グレー','gray'),O('ブルーグレー','blue-gray',['elegant']),O('シルバー','silver',['elegant']),O('茶','brown'),O('チョコレート','chocolate brown'),O('クリーム','cream',['cute']),O('ベージュ','beige'),O('オレンジ','orange',['cute','chaos']),O('レッド','red ginger'),O('フォーン','fawn')],
  pattern:[O('単色','solid-colored coat'),O('ハチワレ','bicolor tuxedo-like facial split',['japan','cute']),O('タキシード','black-and-white tuxedo pattern'),O('三毛','calico pattern',['japan','cute']),O('サビ','tortoiseshell pattern'),O('キジトラ','brown mackerel tabby',['japan','natural']),O('茶トラ','orange mackerel tabby',['cute']),O('サバトラ','silver mackerel tabby',['japan']),O('クラシックタビー','classic swirled tabby'),O('スポッテッドタビー','spotted tabby'),O('ティックドタビー','ticked tabby'),O('カラーポイント','colorpoint pattern',['cute']),O('ブルーポイント','blue point pattern',['cute']),O('ミテッド','mitted point pattern'),O('バン','van pattern'),O('ハーレクイン','harlequin bicolor pattern'),O('スモーク','smoke coat'),O('シェーデッド','shaded coat'),O('チンチラ','chinchilla silver shading',['elegant']),O('ロゼット','rosetted Bengal pattern',['wild']),O('マーブル','marbled pattern')],
  tail:[O('普通','natural tail'),O('短い','short tail'),O('長い','long tail'),O('極太','thick tail'),O('細い','thin elegant tail'),O('ふさふさ','very fluffy tail',['cute','photo']),O('かぎ尻尾','kinked hook tail',['japan']),O('ボブテイル','bobtail',['japan']),O('丸まっている','curled tail'),O('毛が逆立つ','puffed-up tail',['chaos'])],
  whiskers:[O('自然','natural whiskers'),O('長い','long whiskers',['photo']),O('短め','short whiskers'),O('多め','dense whiskers'),O('左右非対称','slightly asymmetrical whiskers')],
  expression:[O('リラックス','relaxed expression',['natural']),O('満足そう','content expression',['cute']),O('眠そう','sleepy expression',['cute']),O('好奇心','curious expression'),O('驚き','surprised expression'),O('警戒','alert expression'),O('不満','slightly annoyed expression',['chaos']),O('激怒','furious expression',['chaos']),O('ドヤ顔','smug confident expression',['chaos']),O('申し訳なさそう','guilty-looking expression',['cute']),O('虚無','blank existential stare',['chaos']),O('悪巧み','mischievous scheming expression',['chaos'])],
  mouth:[O('閉じる','mouth closed'),O('少し開く','mouth slightly open'),O('あくび','yawning',['cute']),O('舌ペロ','tiny tongue sticking out',['cute']),O('鳴いている','meowing'),O('シャー','hissing',['chaos'])],
  gaze:[O('カメラ目線','looking directly at camera',['photo']),O('少し横を見る','looking slightly off-camera'),O('上を見る','looking upward'),O('下を見る','looking downward'),O('遠くを見る','gazing into the distance',['cinema']),O('おもちゃを見る','focused on a toy',['cute']),O('別の猫を見る','looking at another cat')],
  pose:[O('香箱座り','loaf position',['cute']),O('普通に座る','sitting naturally'),O('伏せる','lying sphinx-like'),O('丸まる','curled up'),O('ヘソ天','lying belly-up',['cute','chaos']),O('横向きに寝る','sleeping on its side'),O('立つ','standing'),O('二足立ち','standing on hind legs',['chaos']),O('振り返る','looking back over shoulder',['cinema']),O('伸びをする','stretching body'),O('ジャンプ中','mid-jump',['photo']),O('着地直前','about to land',['photo'])],
  action:[O('何もしない','simply existing'),O('寝る','sleeping',['cute']),O('毛づくろい','grooming itself'),O('あくび','yawning'),O('水を飲む','drinking water'),O('ご飯を食べる','eating food'),O('窓の外を見る','watching through a window',['cinema']),O('猫じゃらしで遊ぶ','playing with a feather wand',['cute']),O('ボールを追う','chasing a ball'),O('箱に入る','squeezed into a cardboard box',['cute','chaos']),O('紙袋に入る','inside a paper bag',['chaos']),O('キーボードに乗る','sitting on a computer keyboard',['chaos']),O('物を棚から落とす','pushing an object off a shelf',['chaos']),O('全力疾走','sprinting at full speed',['photo']),O('虫を追う','chasing a tiny insect'),O('何もない壁を見る','staring intensely at an empty wall',['chaos'])],
  outfit:[O('何も着けない','no clothing or accessories',['natural']),O('細い首輪','thin collar'),O('鈴付き首輪','collar with a small bell',['cute']),O('リボン','small ribbon',['cute']),O('蝶ネクタイ','bow tie',['cute']),O('バンダナ','bandana'),O('丸メガネ','round glasses',['chaos']),O('サングラス','sunglasses',['chaos']),O('ニット帽','knit cap'),O('王冠','tiny crown',['fantasy']),O('パーカー','hoodie'),O('スーツ','tiny formal suit',['chaos']),O('着物','traditional kimono',['japan']),O('宇宙服','miniature spacesuit',['fantasy','chaos']),O('魔法使い','wizard outfit',['fantasy']),O('サムライ','samurai-inspired armor',['japan','fantasy'])],
  location:[O('明るいリビング','bright cozy living room',['cute','natural']),O('ベッドの上','soft bed',['cute']),O('キッチン','home kitchen'),O('和室','traditional Japanese tatami room',['japan']),O('古民家','old Japanese wooden house',['japan','cinema']),O('カフェ','cozy café'),O('本屋','quiet bookstore'),O('オフィス','modern office'),O('公園','green park'),O('草原','open meadow',['photo']),O('森','lush forest',['fantasy','photo']),O('海辺','seaside'),O('雪原','snowy field',['cinema']),O('神社','Shinto shrine grounds',['japan','cinema']),O('商店街','Japanese shopping street',['japan']),O('東京の路地','narrow Tokyo alley',['japan','cinema']),O('渋谷の交差点','Shibuya crossing in Tokyo',['japan','cyber']),O('秋葉原','Akihabara street',['japan','cyber']),O('月面','surface of the Moon',['fantasy']),O('宇宙船','inside a spacecraft',['fantasy']),O('サイバーパンク都市','neon cyberpunk megacity',['cyber']),O('魔法学校','fantasy magic academy',['fantasy']),O('空中都市','floating city in the sky',['fantasy']),O('海底都市','underwater city',['fantasy','chaos'])],
  density:[O('背景ほぼ無し','minimal clean background'),O('シンプル','simple uncluttered background'),O('普通','moderately detailed background'),O('高密度','richly detailed environment',['cinema']),O('超高密度','extremely dense world-building details',['fantasy','cyber'])],
  time:[O('夜明け','dawn'),O('朝','morning',['cute']),O('昼','daytime',['natural']),O('午後','afternoon'),O('夕方','golden-hour evening',['cinema']),O('日没直後','blue hour',['cinema']),O('夜','night',['cinema','cyber']),O('深夜','late night',['cyber'])],
  weather:[O('室内・指定なし','weather not visible'),O('快晴','clear sunny weather'),O('薄曇り','soft overcast sky',['photo']),O('雨','rainy weather',['cinema']),O('豪雨','heavy rain',['cinema']),O('雪','gentle snowfall',['cute']),O('吹雪','snowstorm',['cinema']),O('霧','misty fog',['fantasy']),O('雷雨','thunderstorm',['cinema'])],
  season:[O('指定なし','season unspecified'),O('春','spring'),O('夏','summer'),O('秋','autumn',['cinema']),O('冬','winter',['cute'])],
  light:[O('柔らかな自然光','soft natural light',['photo']),O('窓からの光','soft window light',['photo']),O('ゴールデンアワー','warm golden-hour light',['cinema']),O('曇天の拡散光','soft overcast diffuse light',['photo']),O('スタジオ照明','controlled studio lighting',['photo']),O('白熱灯','warm tungsten interior light'),O('キャンドル','candlelight',['cinema','fantasy']),O('月明かり','moonlight',['cinema']),O('ネオン','colorful neon lighting',['cyber'])],
  lightDir:[O('自然','natural light direction'),O('正面','front lighting'),O('斜め前','three-quarter front lighting'),O('サイド','side lighting',['cinema']),O('逆光','backlighting with rim light',['cinema']),O('トップ','top lighting')],
  lightQuality:[O('柔らかい','soft diffused light',['cute','photo']),O('標準','balanced contrast'),O('硬い','hard directional light',['cinema']),O('霧っぽい','hazy volumetric light',['fantasy'])],
  temp:[O('暖色','warm color temperature'),O('ニュートラル','neutral white balance',['photo']),O('寒色','cool color temperature'),O('暖色＋寒色ミックス','warm and cool mixed lighting',['cinema','cyber'])],
  medium:[O('スマホ写真','natural smartphone photo',['natural']),O('ミラーレス写真','high-end mirrorless camera photograph',['photo']),O('一眼レフ','DSLR photograph',['photo']),O('中判','medium-format photograph',['photo']),O('35mmフィルム','35mm film photograph',['cinema']),O('インスタント写真','instant film photo'),O('CCTV','security camera footage',['chaos'])],
  lens:[O('14mm','14mm ultra-wide lens'),O('24mm','24mm wide-angle lens'),O('35mm','35mm lens',['natural']),O('50mm','50mm standard lens',['photo']),O('85mm','85mm portrait lens',['photo','cute']),O('135mm','135mm telephoto lens'),O('200mm','200mm telephoto lens'),O('400mm','400mm super-telephoto lens'),O('マクロ','macro lens',['photo'])],
  aperture:[O('f/1.2','f/1.2, extremely shallow depth of field'),O('f/1.4','f/1.4'),O('f/2','f/2'),O('f/2.8','f/2.8',['photo']),O('f/4','f/4'),O('f/5.6','f/5.6'),O('f/8','f/8'),O('f/11','f/11, deep depth of field')],
  angle:[O('猫の目線','camera at cat eye level',['photo','cute']),O('地面すれすれ','ground-level low angle'),O('ローアングル','low-angle shot',['cinema']),O('人間の目線','human eye-level shot'),O('ハイアングル','high-angle shot'),O('真上','top-down shot')],
  framing:[O('顔アップ','extreme close-up of face'),O('胸から上','close portrait'),O('全身','full-body shot',['photo']),O('少し引き','medium-wide shot'),O('かなり引き','wide environmental shot',['cinema'])],
  composition:[O('自然','natural balanced composition'),O('中央','centered composition',['cute']),O('三分割','rule-of-thirds composition',['photo']),O('左右対称','symmetrical composition'),O('左寄せ','subject placed left of frame'),O('右寄せ','subject placed right of frame'),O('対角線','dynamic diagonal composition',['cinema']),O('額縁構図','frame-within-a-frame composition',['cinema'])],
  depth:[O('極浅','extremely shallow depth of field'),O('浅い','shallow depth of field with creamy bokeh',['photo','cute']),O('普通','moderate depth of field'),O('深い','deep focus')],
  motion:[O('完全静止','crisp frozen motion'),O('自然','natural shutter rendering'),O('少し動体感','subtle motion blur'),O('背景流し','panning shot with streaked background',['photo']),O('長時間露光','long-exposure trails',['cyber','chaos'])],
  style:[O('フォトリアル','photorealistic',['photo']),O('自然なペット写真','natural pet photography',['photo','cute']),O('雑誌広告','premium editorial advertising photo',['photo']),O('映画スチル','cinematic film still',['cinema']),O('ドキュメンタリー','documentary photography',['natural']),O('アニメ','clean anime illustration',['cute']),O('絵本','soft children’s picture-book illustration',['cute']),O('水彩','delicate watercolor illustration'),O('油絵','rich oil painting'),O('鉛筆画','detailed pencil drawing'),O('クレヨン','playful crayon illustration'),O('3DCG','high-quality 3D render'),O('トゥーンCG','stylized toon 3D render',['cute']),O('クレイ','handmade clay figure style',['cute']),O('ぬいぐるみ','plush toy aesthetic',['cute']),O('ピクセルアート','pixel art'),O('16bitゲーム','16-bit game sprite aesthetic'),O('ローポリ','low-poly 3D style')],
  detail:[O('自然','natural detail'),O('高精細','high detail'),O('超高精細','extremely high detail',['photo']),O('毛一本一本','individual fur strands sharply resolved',['photo']),O('映画品質','feature-film production quality',['cinema'])],
  colorMood:[O('自然色','natural color palette',['photo']),O('パステル','soft pastel palette',['cute']),O('暖色','warm cozy palette'),O('寒色','cool calm palette'),O('低彩度','muted desaturated palette',['cinema']),O('高彩度','vivid colorful palette'),O('ネオン','neon magenta-cyan palette',['cyber']),O('フィルム調','subtle filmic color grading',['cinema'])],
  aspect:[O('1:1 正方形','1:1 square'),O('4:5 縦','4:5 portrait'),O('3:4 縦','3:4 portrait'),O('9:16 スマホ縦','9:16 vertical'),O('3:2 横','3:2 landscape'),O('16:9 横','16:9 cinematic landscape',['cinema']),O('21:9 シネマ','21:9 ultrawide cinematic',['cinema'])]
};

const categories=[
C('identity','🐱','猫そのもの','種類・年齢・体格・性格',[F('breed','猫種',1,cats.breed,1),F('age','年齢',1,cats.age,4),F('sex','性別',2,cats.sex,0),F('body','体格',1,cats.body,2),F('personality','性格',2,cats.personality,0)]),
C('face','🎀','顔・頭','顔型・目・耳・鼻',[F('head','顔型',2,cats.head,0),F('eyeColor','目の色',1,cats.eyeColor,0),F('eyeShape','目の形',2,cats.eyeShape,0),F('pupil','瞳孔',3,cats.pupil,0),F('ears','耳の形',2,cats.ears,0),F('earPose','耳の向き',3,cats.earPose,0),F('nose','鼻',3,cats.nose,0)]),
C('fur','🧶','毛・柄','長さ・質感・色・模様',[F('furLength','毛の長さ',1,cats.furLength,4),F('furTexture','毛質',1,cats.furTexture,2),F('furDensity','毛量',2,cats.furDensity,2),F('color','ベース色',1,cats.color,7),F('pattern','柄',1,cats.pattern,12),R('whiteRatio','白毛の割合',3,0,100,5,55,'%'),F('tail','しっぽ',2,cats.tail,5),F('whiskers','ヒゲ',3,cats.whiskers,0)]),
C('mood','😽','表情・視線','顔つき・口・見る方向',[F('expression','表情',1,cats.expression,1),F('mouth','口',2,cats.mouth,0),F('gaze','視線',2,cats.gaze,0)]),
C('action','🐾','ポーズ・行動','座り方・動き',[F('pose','ポーズ',1,cats.pose,0),F('action','行動',1,cats.action,0)]),
C('fashion','👑','アクセサリー','服・首輪・小物',[F('outfit','服・小物',2,cats.outfit,0)]),
C('scene','🏡','背景・世界','場所・時間・天候',[F('location','場所',1,cats.location,0),F('density','背景密度',2,cats.density,2),F('time','時間帯',2,cats.time,2),F('weather','天候',2,cats.weather,0),F('season','季節',3,cats.season,0)]),
C('light','💡','光','光源・方向・硬さ・色温度',[F('light','光源',1,cats.light,0),F('lightDir','光の方向',3,cats.lightDir,0),F('lightQuality','光の質',2,cats.lightQuality,0),F('temp','色温度',3,cats.temp,1)]),
C('camera','📷','カメラ','機材・レンズ・構図',[F('medium','撮影媒体',2,cats.medium,1),F('lens','焦点距離',1,cats.lens,4),F('aperture','絞り',3,cats.aperture,3),F('angle','カメラ位置',1,cats.angle,0),F('framing','被写体サイズ',2,cats.framing,2),F('composition','構図',2,cats.composition,2),F('depth','被写界深度',2,cats.depth,1),F('motion','シャッター表現',3,cats.motion,0)]),
C('style','✨','画風・仕上げ','表現・色・比率',[F('style','作風',1,cats.style,0),F('detail','ディテール',2,cats.detail,2),F('colorMood','色調',2,cats.colorMood,0),F('aspect','アスペクト比',1,cats.aspect,1)])
];

const negativeOptions=[['extraLimbs','余分な脚なし','no extra legs or limbs'],['extraTail','余分なしっぽなし','no extra tails'],['extraEars','余分な耳なし','no extra ears'],['badEyes','目の崩れなし','no malformed or mismatched eyes'],['badPaws','肉球・足の崩れなし','no malformed paws'],['badFur','不自然な毛なし','no unnatural fur artifacts'],['text','文字なし','no text'],['logo','ロゴなし','no logos'],['watermark','透かしなし','no watermark'],['humanHands','人間の手なし','no human hands'],['otherAnimals','他の動物なし','no other animals'],['collar','首輪なし','no collar unless specified']];
const state={values:{},locks:{},mode:'easy',lang:'ja',target:'chatgpt',negatives:new Set(['extraLimbs','extraTail','extraEars','badEyes','badPaws','text','watermark']),profiles:[]};
let deferredInstall=null;
function defaults(){categories.flatMap(c=>c.fields).forEach(f=>state.values[f.id]=f.type==='range'?f.default:f.options[f.default].ja);}defaults();
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function optionByValue(field,value){return field.options?.find(o=>o.ja===value)||field.options?.[0];}
function findField(id){return categories.flatMap(c=>c.fields).find(f=>f.id===id);}
function valueText(id,lang='ja'){const f=findField(id);if(!f)return'';if(f.type==='range')return `${state.values[id]}${f.suffix||''}`;return optionByValue(f,state.values[id])?.[lang]||state.values[id];}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1800);}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function renderNav(){const nav=$('#categoryNav');nav.innerHTML=categories.map((c,i)=>`<button class="nav-btn ${i===0?'active':''}" data-jump="${c.id}"><span class="nav-icon">${c.icon}</span><span>${c.label}</span></button>`).join('');nav.addEventListener('click',e=>{const b=e.target.closest('[data-jump]');if(!b)return;document.getElementById(`section-${b.dataset.jump}`)?.scrollIntoView({behavior:'smooth',block:'start'});});}
function fieldCard(f){const locked=!!state.locks[f.id];let control='';if(f.type==='range')control=`<input data-field="${f.id}" type="range" min="${f.min}" max="${f.max}" step="${f.step}" value="${state.values[f.id]}"><div class="range-value">${state.values[f.id]}${f.suffix}</div>`;else control=`<select data-field="${f.id}">${f.options.map(o=>`<option value="${esc(o.ja)}" ${o.ja===state.values[f.id]?'selected':''}>${esc(o.ja)}</option>`).join('')}</select>`;return `<article class="setting-card ${locked?'is-locked':''}" data-card="${f.id}" data-level="${f.level}" data-search="${esc((f.label+' '+(f.options||[]).map(o=>o.ja+' '+o.en).join(' ')).toLowerCase())}"><div class="setting-label-row"><span class="setting-label">${f.label}</span><span class="setting-actions"><button class="mini-btn ${locked?'locked':''}" data-action="lock" data-field="${f.id}" title="ロック">${locked?'🔒':'🔓'}</button><button class="mini-btn" data-action="random" data-field="${f.id}" title="この項目だけランダム">🎲</button></span></div>${control}</article>`;}
function renderSettings(){const root=$('#settingsRoot');root.innerHTML=categories.map(c=>`<section class="settings-section" id="section-${c.id}" data-category="${c.id}"><div class="section-head"><span class="big-icon">${c.icon}</span><div><h3>${c.label}</h3><small>${c.desc}</small></div></div><div class="settings-grid">${c.fields.map(fieldCard).join('')}</div></section>`).join('');root.addEventListener('change',e=>{const el=e.target.closest('[data-field]');if(!el)return;const f=findField(el.dataset.field);state.values[f.id]=f.type==='range'?Number(el.value):el.value;updateAll();});root.addEventListener('input',e=>{const el=e.target.closest('input[type=range][data-field]');if(!el)return;const f=findField(el.dataset.field);state.values[f.id]=Number(el.value);el.closest('.setting-card').querySelector('.range-value').textContent=`${el.value}${f.suffix}`;updateAll(false);});root.addEventListener('click',e=>{const btn=e.target.closest('[data-action]');if(!btn)return;const id=btn.dataset.field;if(btn.dataset.action==='lock'){state.locks[id]=!state.locks[id];syncLockCard(id);}if(btn.dataset.action==='random'){randomizeField(id,'normal');syncField(id);updateAll();}});applyMode();}
function syncLockCard(id){const card=document.querySelector(`[data-card="${id}"]`),b=card?.querySelector('[data-action="lock"]');if(!card||!b)return;card.classList.toggle('is-locked',!!state.locks[id]);b.classList.toggle('locked',!!state.locks[id]);b.textContent=state.locks[id]?'🔒':'🔓';}
function syncField(id){const f=findField(id),el=document.querySelector(`[data-field="${id}"]`);if(!f||!el)return;el.value=state.values[id];if(f.type==='range')el.closest('.setting-card').querySelector('.range-value').textContent=`${state.values[id]}${f.suffix}`;}
function modeLevel(){return state.mode==='easy'?1:state.mode==='detail'?2:3;}
function applyMode(){const lvl=modeLevel(),q=$('#settingSearch')?.value.trim().toLowerCase()||'';let n=0;$$('.setting-card').forEach(card=>{const show=Number(card.dataset.level)<=lvl&&(!q||card.dataset.search.includes(q));card.hidden=!show;if(show)n++;});$$('.settings-section').forEach(sec=>sec.hidden=!sec.querySelector('.setting-card:not([hidden])'));$('#visibleCount').textContent=n;$$('.mode-btn').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));}
function weightedPick(field,preset){if(field.type==='range')return Math.round((field.min+Math.random()*(field.max-field.min))/field.step)*field.step;let pool=field.options;if(preset!=='normal'&&preset!=='chaos'){const tagged=pool.filter(o=>o.tags?.includes(preset));if(tagged.length)pool=Math.random()<.78?tagged:pool;}if(preset==='chaos'){const tagged=pool.filter(o=>o.tags?.includes('chaos')||o.tags?.includes('fantasy')||o.tags?.includes('cyber'));if(tagged.length)pool=Math.random()<.85?tagged:pool;}return pool[Math.floor(Math.random()*pool.length)].ja;}
function randomizeField(id,preset){if(state.locks[id])return;const f=findField(id);state.values[id]=weightedPick(f,preset);}
function presetLabel(p){return({normal:'おまかせ猫',cute:'かわいい猫',photo:'写真猫',cinema:'映画猫',japan:'日本猫',fantasy:'幻想猫',cyber:'サイバー猫',chaos:'カオス猫'})[p]||'猫';}
function randomize(preset){categories.flatMap(c=>c.fields).forEach(f=>randomizeField(f.id,preset));const forced={cute:{expression:'満足そう',furTexture:'ふわふわ',eyeShape:'まん丸',style:'自然なペット写真'},photo:{style:'フォトリアル',medium:'ミラーレス写真',light:'柔らかな自然光'},cinema:{style:'映画スチル',composition:'三分割',lightQuality:'硬い',colorMood:'フィルム調'},japan:{location:'和室',breed:'雑種・日本猫',pattern:'三毛',outfit:'何も着けない'},fantasy:{location:'魔法学校',outfit:'魔法使い',style:'映画スチル'},cyber:{location:'サイバーパンク都市',light:'ネオン',colorMood:'ネオン',time:'夜'},chaos:{expression:'虚無'}}[preset]||{};Object.entries(forced).forEach(([k,v])=>{if(!state.locks[k])state.values[k]=v;});categories.flatMap(c=>c.fields).forEach(f=>syncField(f.id));updateAll();toast(`${presetLabel(preset)} を錬成しました 🐾`);}
function selectedSentences(lang){const v=id=>valueText(id,lang);if(lang==='ja')return [`${v('breed')}。${v('age')}、${v('sex')}、${v('body')}。性格は${v('personality')}。`,`顔は${v('head')}。${v('eyeColor')}で${v('eyeShape')}、瞳孔は${v('pupil')}。耳は${v('ears')}で${v('earPose')}、鼻は${v('nose')}。`,`${v('color')}を基調に${v('pattern')}。${v('furLength')}、${v('furTexture')}、${v('furDensity')}。白毛の割合は約${v('whiteRatio')}。しっぽは${v('tail')}、ヒゲは${v('whiskers')}。`,`表情は${v('expression')}、口は${v('mouth')}、${v('gaze')}。${v('pose')}で、${v('action')}。${v('outfit')}。`,`場所は${v('location')}。${v('density')}、${v('time')}、${v('weather')}、${v('season')}。`,`${v('light')}、${v('lightDir')}、${v('lightQuality')}、${v('temp')}。`,`${v('medium')}、${v('lens')}、${v('aperture')}、${v('angle')}、${v('framing')}、${v('composition')}、${v('depth')}、${v('motion')}。`,`作風は${v('style')}。${v('detail')}、${v('colorMood')}、アスペクト比${v('aspect')}。`];return [`${v('breed')}, ${v('age')}, ${v('sex')}, ${v('body')}, with a ${v('personality')} personality.`,`${v('head')}, ${v('eyeColor')}, ${v('eyeShape')}, ${v('pupil')}; ${v('ears')}, ${v('earPose')}, ${v('nose')}.`,`${v('color')} coat with ${v('pattern')}, ${v('furLength')}, ${v('furTexture')}, ${v('furDensity')}, approximately ${v('whiteRatio')} white fur, ${v('tail')}, ${v('whiskers')}.`,`${v('expression')}, ${v('mouth')}, ${v('gaze')}; ${v('pose')}, ${v('action')}, ${v('outfit')}.`,`Scene: ${v('location')}, ${v('density')}, ${v('time')}, ${v('weather')}, ${v('season')}.`,`Lighting: ${v('light')}, ${v('lightDir')}, ${v('lightQuality')}, ${v('temp')}.`,`Camera: ${v('medium')}, ${v('lens')}, ${v('aperture')}, ${v('angle')}, ${v('framing')}, ${v('composition')}, ${v('depth')}, ${v('motion')}.`,`Style: ${v('style')}, ${v('detail')}, ${v('colorMood')}, aspect ratio ${v('aspect')}.`];}
function negatives(lang){return negativeOptions.filter(([id])=>state.negatives.has(id)).map(x=>lang==='ja'?x[1]:x[2]);}
function aspectMJ(label){const m=label.match(/(\d+):(\d+)/);return m?` --ar ${m[1]}:${m[2]}`:'';}
function generatePrompt(){const lang=state.lang,parts=selectedSentences(lang),note=$('#customNote')?.value.trim(),neg=negatives(lang);let body=parts.join(lang==='ja'?'\n':' ');if(note)body+=lang==='ja'?`\n追加指定：${note}`:` Additional direction: ${note}`;if(state.target==='chatgpt')return lang==='ja'?`以下の条件で猫の画像を生成してください。記載した特徴・構図を優先し、自然で破綻のない猫として表現してください。\n\n${body}\n\n避ける要素：${neg.join('、')}。`:`Generate an image of a cat using the following specification. Preserve the described appearance, pose, composition, and scene while keeping feline anatomy natural and coherent.\n\n${body}\n\nAvoid: ${neg.join(', ')}.`;if(state.target==='gemini')return lang==='ja'?`猫の画像を1枚生成。以下の仕様を視覚的に忠実に反映してください。特に猫種、毛柄、目、ポーズ、画角、照明の整合性を優先してください。\n\n${body}\n\n除外：${neg.join('、')}。`:`Create one cat image faithfully following this visual specification. Prioritize consistency of breed, coat pattern, eyes, pose, camera angle and lighting.\n\n${body}\n\nExclude: ${neg.join(', ')}.`;if(state.target==='midjourney'){const base=parts.join(' ');return `${base}${note?' '+note:''} --no ${neg.join(', ')}${aspectMJ(valueText('aspect','ja'))}`;}if(state.target==='flux')return `${parts.join(' ')}${note?' '+note:''}\n\nNegative prompt: ${neg.join(', ')}`;return body+(neg.length?(lang==='ja'?`\n\n避ける要素：${neg.join('、')}`:`\n\nAvoid: ${neg.join(', ')}`):'');}
function updatePrompt(){const out=$('#promptOutput');if(out)out.value=generatePrompt();}
function updatePreview(){const colorMap={'白':'#f8f5f1','黒':'#403b45','グレー':'#99949c','ブルーグレー':'#8998aa','シルバー':'#c7c5c9','茶':'#9c715b','チョコレート':'#765349','クリーム':'#ead9bd','ベージュ':'#ceb89f','オレンジ':'#d99458','レッド':'#bd704d','フォーン':'#cdb8a6'};const eyeMap={'ブルー':'#78bfe6','水色':'#9edbe1','グリーン':'#80bd89','黄緑':'#a7c76c','琥珀':'#d7a74f','ゴールド':'#e1bf54','銅色':'#c9864f','ブラウン':'#8b684e','オッドアイ':'#77bde0'};document.documentElement.style.setProperty('--cat',colorMap[state.values.color]||'#c8b3a6');document.documentElement.style.setProperty('--cat-eye',eyeMap[state.values.eyeColor]||'#77b7d6');const patch=['単色','スモーク','シェーデッド'].includes(state.values.pattern)?'#ffffff00':'#f8efea';document.documentElement.style.setProperty('--cat2',patch);const shape=state.values.pupil;$$('.pupil').forEach(p=>{if(shape==='細い縦長'){p.setAttribute('rx','2.5');p.setAttribute('ry','11')}else if(shape==='真ん丸'){p.setAttribute('rx','8');p.setAttribute('ry','8')}else if(shape==='大きめ'){p.setAttribute('rx','7');p.setAttribute('ry','11')}else{p.setAttribute('rx','5');p.setAttribute('ry','10')}});$('#catSummary').textContent=`${state.values.breed} · ${state.values.pattern} · ${state.values.eyeColor}`;$('#previewBadge').textContent=state.values.expression==='虚無'?'VOID CAT':'TODAY\'S CAT';}
function updateAll(prompt=true){updatePreview();if(prompt)updatePrompt();persistDraft();}
function renderNegatives(){const root=$('#negativeGrid');root.innerHTML=negativeOptions.map(([id,ja])=>`<button class="negative-chip ${state.negatives.has(id)?'active':''}" data-neg="${id}">${ja}</button>`).join('');root.addEventListener('click',e=>{const b=e.target.closest('[data-neg]');if(!b)return;const id=b.dataset.neg;state.negatives.has(id)?state.negatives.delete(id):state.negatives.add(id);b.classList.toggle('active',state.negatives.has(id));updatePrompt();});}
function loadProfiles(){try{state.profiles=JSON.parse(localStorage.getItem('catbuilder.profiles')||'[]')}catch{state.profiles=[]}renderProfiles();}
function renderProfiles(){const root=$('#profilesList');if(!state.profiles.length){root.innerHTML='<p class="microcopy">まだ保存された猫はいません。理想の1匹ができたら名前をつけて保存できます。</p>';return;}root.innerHTML=state.profiles.map((p,i)=>`<div class="profile-item"><div><strong>🐈 ${esc(p.name)}</strong><small>${esc(p.values.breed)} · ${esc(p.values.pattern)}</small></div><span class="profile-item-actions"><button class="mini-btn" data-load-profile="${i}">↩</button><button class="mini-btn" data-delete-profile="${i}">×</button></span></div>`).join('');}
function saveProfile(){const name=$('#profileName').value.trim();if(!name)return toast('猫の名前を入れてください 🐱');state.profiles.unshift({name,values:{...state.values},locks:{...state.locks},note:$('#customNote').value});state.profiles=state.profiles.slice(0,20);localStorage.setItem('catbuilder.profiles',JSON.stringify(state.profiles));$('#profileName').value='';renderProfiles();toast(`${name} をMY CATSに保存しました 💗`);}
function applyProfile(i){const p=state.profiles[i];if(!p)return;state.values={...state.values,...p.values};state.locks={...p.locks};$('#customNote').value=p.note||'';categories.flatMap(c=>c.fields).forEach(f=>{syncField(f.id);syncLockCard(f.id)});updateAll();toast(`${p.name} を呼び出しました 🐾`);}
function deleteProfile(i){state.profiles.splice(i,1);localStorage.setItem('catbuilder.profiles',JSON.stringify(state.profiles));renderProfiles();}
async function copyPrompt(){try{await navigator.clipboard.writeText($('#promptOutput').value);toast('プロンプトをコピーしました 📋')}catch{$('#promptOutput').select();document.execCommand('copy');toast('コピーしました 📋')}}
async function sharePrompt(){const text=$('#promptOutput').value;if(navigator.share){try{await navigator.share({title:'Cat Builder Prompt',text});return}catch(e){if(e.name==='AbortError')return}}await copyPrompt();}
async function openAI(type){await copyPrompt();const prompt=encodeURIComponent($('#promptOutput').value);const urls={chatgpt:`https://chatgpt.com/?q=${prompt}`,gemini:'https://gemini.google.com/app',claude:'https://claude.ai/new'};window.open(urls[type],'_blank','noopener,noreferrer');toast(`${type==='chatgpt'?'ChatGPT':type==='gemini'?'Gemini':'Claude'} を開きます。入力されない場合は貼り付けてください 🐾`);}
function persistDraft(){try{localStorage.setItem('catbuilder.draft',JSON.stringify({values:state.values,locks:state.locks,mode:state.mode,lang:state.lang,target:state.target,negatives:[...state.negatives],note:$('#customNote')?.value||''}))}catch{}}
function loadDraft(){try{const d=JSON.parse(localStorage.getItem('catbuilder.draft')||'null');if(!d)return;state.values={...state.values,...d.values};state.locks=d.locks||{};state.mode=d.mode||'easy';state.lang=d.lang||'ja';state.target=d.target||'chatgpt';state.negatives=new Set(d.negatives||[]);setTimeout(()=>{$('#customNote').value=d.note||'';updateAll()},0)}catch{}}
function initEvents(){$$('.mode-btn').forEach(b=>b.addEventListener('click',()=>{state.mode=b.dataset.mode;applyMode();persistDraft();}));$('#settingSearch').addEventListener('input',applyMode);$('#randomPresets').addEventListener('click',e=>{const b=e.target.closest('[data-preset]');if(b)randomize(b.dataset.preset)});$('#lockAllBtn').addEventListener('click',()=>{const all=categories.flatMap(c=>c.fields);const shouldLock=all.some(f=>!state.locks[f.id]);all.forEach(f=>state.locks[f.id]=shouldLock);all.forEach(f=>syncLockCard(f.id));$('#lockAllBtn').textContent=shouldLock?'🔓 全解除':'🔒 全ロック';persistDraft();});$$('.lang-btn').forEach(b=>b.addEventListener('click',()=>{state.lang=b.dataset.lang;$$('.lang-btn').forEach(x=>x.classList.toggle('active',x===b));updatePrompt();persistDraft();}));$('#targetTabs').addEventListener('click',e=>{const b=e.target.closest('[data-target]');if(!b)return;state.target=b.dataset.target;$$('.target-tab').forEach(x=>x.classList.toggle('active',x===b));updatePrompt();persistDraft();});$('#customNote').addEventListener('input',()=>{updatePrompt();persistDraft()});$('#copyBtn').addEventListener('click',copyPrompt);$('#shareBtn').addEventListener('click',sharePrompt);$$('[data-ai]').forEach(b=>b.addEventListener('click',()=>openAI(b.dataset.ai)));$('#saveProfileBtn').addEventListener('click',saveProfile);$('#profilesList').addEventListener('click',e=>{const l=e.target.closest('[data-load-profile]'),d=e.target.closest('[data-delete-profile]');if(l)applyProfile(Number(l.dataset.loadProfile));if(d)deleteProfile(Number(d.dataset.deleteProfile));});$('#themeBtn').addEventListener('click',()=>{document.body.classList.toggle('dark');const dark=document.body.classList.contains('dark');$('#themeBtn').textContent=dark?'☀️':'🌙';localStorage.setItem('catbuilder.dark',dark?'1':'0')});$('#installBtn').addEventListener('click',async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#installBtn').hidden=true;});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').hidden=false;});const sections=$$('.settings-section');if('IntersectionObserver'in window){const io=new IntersectionObserver(entries=>{const current=entries.filter(x=>x.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(current){$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.jump===current.target.dataset.category));}},{rootMargin:'-25% 0px -65% 0px',threshold:[0,.1,.3]});sections.forEach(s=>io.observe(s));}}
function init(){loadDraft();renderNav();renderSettings();renderNegatives();loadProfiles();initEvents();$$('.lang-btn').forEach(b=>b.classList.toggle('active',b.dataset.lang===state.lang));$$('.target-tab').forEach(b=>b.classList.toggle('active',b.dataset.target===state.target));if(localStorage.getItem('catbuilder.dark')==='1'){document.body.classList.add('dark');$('#themeBtn').textContent='☀️';}updateAll();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}
document.addEventListener('DOMContentLoaded',init);
